package dev.daviekim.stockwave.common

object Constants {
    val companySymbolToName = mapOf(
        "AAPL" to "Apple Inc.",
        "GOOGL" to "Alphabet Inc.(Google)",
        "GOOG" to "Alphabet Inc.(Google)",
        "MSFT" to "Microsoft Corp.",
        "AMZN" to "Amazon.com Inc.",
        "FB" to "Meta Platforms Inc.",
        "TSLA" to "Tesla, Inc.",
        "BRK.A" to "Berkshire Hathaway Inc.",
        "BRK.B" to "Berkshire Hathaway Inc.",
        "JPM" to "JPMorgan Chase & Co.",
        "V" to "Visa Inc.",
        "JNJ" to "Johnson & Johnson",
        "WMT" to "Walmart Inc.",
        "PG" to "Procter & Gamble Co.",
        "MA" to "Mastercard Inc.",
        "NVDA" to "NVIDIA Corporation",
        "UNH" to "UnitedHealth Inc.",
        "HD" to "The Home Depot, Inc.",
        "DIS" to "The Walt Disney Company",
        "BAC" to "Bank of America Corp.",
        "VZ" to "Verizon Com. Inc.",
        "KO" to "The Coca-Cola Co.",
        "MRK" to "Merck & Co., Inc.",
        "PFE" to "Pfizer Inc.",
        "INTC" to "Intel Corporation",
        "NFLX" to "Netflix, Inc.",
        "ADBE" to "Adobe Inc.",
        "CSCO" to "Cisco Systems, Inc.",
        "CMCSA" to "Comcast Corporation",
        "PEP" to "PepsiCo, Inc.",
        "XOM" to "Exxon Mobil Corp.",
        "MCD" to "McDonald's Corp.",
        "BA" to "The Boeing Company",
        "ORCL" to "Oracle Corporation",
        "T" to "AT&T Inc.",
        "NKE" to "NIKE, Inc.",
        "ABT" to "Abbott Laboratories",
        "CRM" to "Salesforce.com, inc.",
        "CVX" to "Chevron Corporation",
        "IBM" to "IBM Corporation",
        "MMM" to "3M Company",
        "TXN" to "Texas Instruments Inc.",
        "UTX" to "Raytheon Technologies Corp.",
        "ACN" to "Accenture plc",
        "BMY" to "Bristol-Myers Squibb Co.",
        "CAT" to "Caterpillar Inc.",
        "DHR" to "Danaher Corporation",
        "GS" to "Goldman Sachs, Inc.",
        "PYPL" to "PayPal Holdings, Inc.",
        "AXP" to "American Express Co.",
        "COST" to "Costco Wholesale Corp."
    )
}